name: "update _version.py"

on:
  push:
    branches: [ main ]
    paths:
      - "setup.cfg"
  pull_request:
    branches: [ main ]
    paths:
      - "setup.cfg"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update version file
        run: sed -n 's/^version\s*=\s*\(.*\)/__version__ = "\1"/p' setup.cfg > jobstorm/_version.py

      - name: commit version file
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: "Schrodinger's Koala"
          author_email: "schrodingers.koala@gmail.com"
          message: "update version file"
          add: "jobstorm/_version.py"
